AI:Main.java Board.java BoardDataCircleStructure.java AidUtility.java CeilingDataStructure.java CellNode.java FindCircleAndCapturedCellAlgorithm.java SimpleBoardCountingAlgorithm.java BoardUpdateAlgorithm.java
	javac Main.java Board.java BoardDataCircleStructure.java AidUtility.java CeilingDataStructure.java CellNode.java FindCircleAndCapturedCellAlgorithm.java SimpleBoardCountingAlgorithm.java BoardUpdateAlgorithm.java
TEST_ALL_INPUT:
	java Main < big_small
	java Main < jonathan_sample
	java Main < lim_test_1
	java Main < lim_test_2
	java Main < lim_test3
	java Main < lim_test4
	java Main < lim_test5
	java Main < mytest
	java Main < testCase1
	java Main < testCase2
	java Main < testCase3
	java Main < testinput
	java Main < testinput2
	java Main < testinput3